name: Update JSON

on:
  repository_dispatch:
    types: [google_sheets_update]

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up GOOGLE_APPLICATION_CREDENTIALS
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json

      - name: Check and create JSON files if they don't exist
        run: |
          if [ ! -f disc_golf_scores.json ]; then
            echo "[]" > disc_golf_scores.json
          fi

      - name: Run Python script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          python process_scores.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SECRET }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add disc_golf_scores.json
          git commit -m 'Update JSON data' || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.REPO_SECRET }}@github.com/gh2os/disc.git || echo "Nothing to push"